### ISSUE TITLE
Hab euch einfach mal zu einem neuen Projekt hinzugefügt

### ISSUE THREAD

**Issue by StruMa-Code** [StruMa-Code/new_budget_book#1]
Denke es wäre leichter und sauberer von Scratch anzufangen.
Vielleicht sollten wir dann hier unsere Clean-Code-Verhalten sammeln:

Meine Vorschläge wären:
- Klassennamen englisch
- Packagenamen englisch
- Methoden englisch doch der bezug auf variablen (den VaraiblenNamen auf deutsch)
- variablen deutsch

Was denkt ihr?

**Comment by TobiasSMI** [comment]
done
